version: '3.2'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  belmondofiora:
    build: .
    restart: always
    ports:
      - "3111:3111"
      - "443:443"
    environment:
      - "Database=mongodb://mongoDB/belmondofiora"
